# Generated by Django 6.0.7 on 2026-08-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_category_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
