name: Run bot

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests flask

      - name: Run bot
        env:
          REMANGA_EMAIL: ${{ secrets.REMANGA_EMAIL }}
          REMANGA_PASSWORD: ${{ secrets.REMANGA_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CUSTOM_PROXY: ${{ secrets.CUSTOM_PROXY }}
        run: python botq.py
