name: Remanga Dungeon Bot

on:
  schedule:
    # Запуск каждые 2 часа (по UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Кнопка для ручного запуска в Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright playwright-stealth requests schedule

      - name: Install Playwright Chromium with system dependencies
        run: |
          playwright install chromium --with-deps

      - name: Run Bot
        env:
          CUSTOM_PROXY: ${{ secrets.CUSTOM_PROXY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REMANGA_EMAIL: ${{ secrets.REMANGA_EMAIL }}
          REMANGA_PASSWORD: ${{ secrets.REMANGA_PASSWORD }}
          RUN_HEADLESS: 'true'
        run: |
          python test/bot.py

      - name: Upload Screenshot on Finish / Error
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-screenshot
          path: "**/error_screenshot.png"
          if-no-files-found: ignore
